export const GET_PASSENGERS_BY_FLIGHTID = "GET_PASSENGERS_BY_FLIGHTID";
export const UPDATE_PASSENGER = "UPDATE_PASSENGER";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
